# Generated by Django 3.0.6 on 2020-05-25 17:19

from django.db import migrations
import shared.fields


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0004_auto_20200521_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='image',
            field=shared.fields.Base64ThumbnailField(null=True, upload_to='store'),
        ),
    ]
